[package]
name = "future"
version = "0.1.0"
authors = ["vmos <vmos@fairblock.io>"]

[dependencies]
futures = "0.1.23"
npnc = "*"

time = {path="../time"}
atom = {path="../atom"}
worker = {path="../worker"}