[workspace]
members = [
  "adler32",
  "base58",
  "atom",
  "bon",
  "data_view",
  "gray",
  "guid",
  "handler",
  "heap",
  "ordmap",
  "rsync",
  "sinfo",
  "slab",
  "time",
  "timer",
  "ucd",
  "util",
  "wcs",
  "wcs_macro",
  "wheel",
  "wtree",
  "deque",
  "dyn_uint",
  "task_pool",
  "apm",
  "file",
  "worker",
  "future",
  "enum_default_macro",
  "pointer",
  "map",
  "ecs",
  "listener",
  "debug_info",
]