[workspace]
members = [
  "adler32",
  "base58",
  "atom",
  "bon",
  "data_view",
  "gray",
  "guid",
  "handler",
  "heap",
  "ordmap",
  "rsync",
  "sinfo",
  "slab",
  "time",
  "timer",
  "util",
  "wcs",
  "wheel",
  "wtree",
  "fast_deque",
  "dyn_uint",
  "task_pool",
  "file",
  "worker",
  "future",
]