[package]
name = "res"
version = "0.1.0"
authors = ["zmythleo <zmythleo@gmail.com>"]

[dependencies]
slab = { path = "../slab"}
deque = {path = "../deque"}
lru = {path = "../lru"}
any = {path="../any"}
share = { path = "../share" }
hash = {path="../hash"}
