[package]
name = "async"
version = "0.1.0"
authors = ["vmos <vmos@fairblock.io>"]
edition = "2018"

[dependencies]
futures = "0.3"
crossbeam-queue = "0.2"
crossbeam-channel = "0.4"
twox-hash = "1.5"
dashmap = "3.7"

[dev-dependencies]
rand = "0.7"
future-parking_lot = "0.3"