[package]
name = "js_proxy_gen_macro"
version = "0.1.0"
authors = ["vmos <vmos@fairblock.io>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
