[package]
name = "index_class"
version = "0.1.0"
authors = ["zmythleo <zmythleo@gmail.com>"]

[dependencies]
slab = {path="../slab"}
map = {path="../map"}
ver_index = {path="../ver_index"}

