[package]
name = "pref"
version = "0.1.0"
authors = ["zmythleo <zmythleo@gmail.com>"]

[dependencies]
sysinfo = "0.8.0"
netstat = "0.7.0"

[target.'cfg(unix)'.dependencies]
psutil = "1.3.1"
walkdir = "2.2.7"