[package]
name = "ecs"
version = "0.1.0"
authors = ["zmythleo <zmythleo@gmail.com>"]

[dependencies]
slab = {path="../slab"}
atom = {path="../atom"}
map = {path="../map"}
any = {path="../any"}
pointer = {path="../pointer"}
listener = {path="../listener"}
time = {path="../time"}
paste = "0.1"
lazy_static = "*"
fnv = "*"
# im = "*"

[[example]]
name = "expanded"

[[example]]
name = "basic"