[package]
name = "ecs"
version = "0.1.0"
authors = ["zmythleo <zmythleo@gmail.com>"]

[dependencies]
slab = {path="../slab"}
atom = {path="../atom"}
map = {path="../map"}
any = {path="../any"}
pointer = {path="../pointer"}
listener = {path="../listener"}
hash = {path="../hash"}
time = {path="../time"}
share = {path="../share"}
paste = "0.1"
lazy_static = "*"
# im = "*"

[features]
runtime = []

[[example]]
name = "expanded"

[[example]]
name = "basic"


