[package]
name = "file"
version = "0.1.0"
authors = ["zmythleo <zmythleo@gmail.com>"]

[dependencies]
npnc = "*"
notify = "*"
lazy_static = "1.3"
atom = { path = "../atom" }
apm = { path = "../apm" }
worker = { path = "../worker" }