[package]
name = "deletable_heap"
version = "0.1.0"
authors = ["zmythleo <zmythleo@gmail.com>"]
edition = "2018"

[dependencies]
ext_heap = {path="../ext_heap"}
index_slotmap = {path="../index_slotmap"}
slotmap = "1.0"
