[package]
name = "wheel"
version = "0.1.0"
authors = ["zmythleo <zmythleo@gmail.com>"]

[dependencies]
heap = {path="../heap"}
index_class = {path="../index_class"}
ver_index = {path="../ver_index"}