[package]
name = "weight"
version = "0.1.0"
authors = ["zmythleo <zmythleo@gmail.com>"]
edition = "2018"

[dependencies]
ext_heap = {path="../ext_heap"}


[dev-dependencies]
pcg_rand = "0.13"
rand_core = "0.6"