[package]
name = "js_proxy_gen"
version = "0.1.0"
authors = ["vmos <vmos@fairblock.io>"]
edition = "2018"

[dependencies]
proc-macro2 = "1.0"
syn = { version = "1.0", features = ["full", "extra-traits"] }
futures = "0.3"
serde = "1.0"
serde_derive = "1.0"
toml = "0.5"
num_cpus = "1.13"
lazy_static = '1.4'
async = { path = "../../pi_lib/async" }
async_file = { path = "../../pi_lib/async_file" }
hash = { path = "../../pi_lib/hash" }
bytes = "0.5"