[package]
name = "ecs_derive"
version = "0.4.0"
authors = ["zmythleo <zmythleo@gmail.com>"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
syn = "1.0"
quote = "1.0"
ecs = {path="../ecs"}
map = {path="../map"}
hashmap = {path="../hashmap"}