[package]
name = "wtree"
version = "0.1.0"
authors = ["zmythleo <zmythleo@gmail.com>"]

[dependencies]
time = {path="../time"}
rand = "0.7"
map = {path="../map"}
index_class = {path="../index_class"}
ver_index = {path="../ver_index"}
