[package]
name = "debug_info"
version = "0.1.0"
authors = ["suncy <suncy@gmail.com>"]
edition = "2018"

[dependencies.web-sys]
version = "*"
optional = true
features = [
	"console",
]

[features]
default = []
print=[]
wasm-bindgen=["web-sys"]