[package]
name = "wcs_macro"
version = "0.1.0"
authors = ["zmythleo <zmythleo@gmail.com>"]

[lib]
proc-macro = true

[dependencies]
quote = "0.6.3"
slab = {path="../slab"}
wcs = {path="f:\\awork\\rust\\pi_lib\\wcs"}

[dependencies.syn]
version = "0.14.4"