[package]
name = "enum_default_macro"
version = "0.1.0"
authors = ["suncy <suncy@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
proc-macro2 = "1.0"

[dependencies.syn]
version = "1.0"