[package]
name = "timer"
version = "0.1.0"
authors = ["suncy <suncy@gmail.com>"]

[dependencies]
atom = {path="../atom"}
wheel = {path="../wheel"}
time = {path="../time"}
lazy_static = "*"
rand = "0.7"