[package]
name = "timer"
version = "0.1.0"
authors = ["zmythleo <zmythleo@gmail.com>"]

[dependencies]
atom = {path="../atom"}
apm = {path="../apm"}
wheel = {path="../wheel"}
time = {path="../time"}
ver_index = {path="../ver_index"}
lazy_static = "*"