[package]
name = "local_timer"
version = "0.1.0"
authors = ["suncy <suncy@gmail.com>"]
edition = "2018"

[dependencies]
heap = {path="../heap"}
time = {path="../time"}
dyn_uint = {path="../dyn_uint"}
arrayvec = "0.7.0"