[package]
name = "static_map"
version = "0.1.0"
authors = ["zmythleo <zmythleo@gmail.com>"]
edition = "2018"

[dependencies]
null = {path="../null"}

[dev-dependencies]
pcg_rand = "0.13"
rand_core = "0.6"