[package]
name = "wcs"
version = "0.1.0"
authors = ["zmythleo <zmythleo@gmail.com>"]

[dependencies]
slab = {path="../slab"}
atom = {path="../atom"}
paste = "0.1"
lazy_static = "*"
fnv = "*"